# Generated by Django 6.0.3 on 2026-04-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_alter_device_hardware_id_alter_license_max_devices'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(help_text='Email at time of purchase (denormalised)', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, help_text='USD→GHS rate used at checkout', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ghs_amount',
            field=models.DecimalField(decimal_places=2, help_text='Charged amount in GHS', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='ghs_pesewas',
            field=models.BigIntegerField(help_text='Amount sent to Paystack (GHS × 100)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='license',
            field=models.OneToOneField(blank=True, help_text='Auto-created after successful payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='licensing.license'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_id',
            field=models.CharField(blank=True, help_text='Paystack transaction ID', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(editable=False, help_text='Paystack payment reference (also used as order ID)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, help_text='Displayed price in USD', max_digits=10),
        ),
    ]
