# Generated by Django 5.2.1 on 2026-02-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(help_text='Unique name for the local system (e.g. microsoft)', max_length=100, unique=True)),
                ('hardware_id', models.CharField(help_text='Lock to specific machine (BIOS/CPU serial)', max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('LITE', 'Lite (Ordinary)'), ('PRO', 'Pro (Connected)'), ('ENTERPRISE', 'Enterprise (Standard)')], default='LITE', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('license_key', models.TextField(blank=True, help_text='Cryptographically signed key for local validation', null=True)),
                ('local_endpoint', models.CharField(blank=True, help_text='VPN or Proxy internal IP', max_length=255, null=True)),
            ],
        ),
    ]
