# Generated by Django 5.2.1 on 2026-02-15 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='client',
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The license key string (e.g. SMARTY-XXXX-YYYY)', max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('LITE', 'Lite (Ordinary)'), ('PRO', 'Pro (Connected)'), ('ENTERPRISE', 'Enterprise (Standard)')], default='LITE', max_length=20)),
                ('max_devices', models.IntegerField(default=1, help_text='Number of devices allowed on this license')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(help_text='Unique Hardware ID of the local machine', max_length=255)),
                ('name', models.CharField(help_text='Friendly name for this device (e.g. Factory Floor 1)', max_length=255)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='licensing.license')),
            ],
            options={
                'unique_together': {('license', 'hardware_id')},
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
    ]
