# Generated by Django 6.0.3 on 2026-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_license_components_device_revocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_devices',
            field=models.IntegerField(default=1),
        ),
    ]
